[package]
name = "ovr_overlay"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ovr_overlay_sys = { path = "sys" }
lazy_static = "1"
thiserror = "1"
derive_more = "0.99"
log = "0.4"


[workspace]
members = ["sys"]
