name: Main CI
on:
  # pull_request:
  push:
    branches:
      - build-testing

jobs:
  test:
    name: Build and test
    # runs-on: ubuntu-22.04
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
      # - name: Install openvr runtime dependencies
      #   run: sudo apt-get update && sudo apt-get install -y libsdl2-2.0-0
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      # - name: Check that docs build
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: doc
      #     args: --all --all-features --no-deps --document-private-items
      - name: Run tests
        uses: actions-rs/cargo@v1
        env:
          RUST_BACKTRACE: 1
        with:
          command: test
          args: --all --all-features --all-targets
